favicon: null
name: Bearded Woodworks
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6379224890843034
  lightness: 0.9831256547477096
  brandStrength: 0.7222222
  brandColors:
    - '#F5F5F5'
    - '#000000'
    - '#646466'
    - '#B7B7B7'
    - '#29ABDF'
  rhythmicContrast: 0.784097061259672
typography_spectrum: 0.4271207
layout_spectrum: 0.7593401030171663
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
